### ISSUE TITLE
Code counts not updated dynamically

### ISSUE THREAD

**Issue by ccbogel** [ccbogel/QualCoder#276]
**Describe the bug**
The count on the coding window does not always correspond to the reality.
There are codes for which you can see associated text but count does not have a value etc.
Or count may be increasing and then suddenly drops back to a low value

**To Reproduce**

**Expected behavior**
A description of what you expected to happen.
Code counts to match when codes are changed or added

**Comment by ccbogel** [comment]
@mirren I have tested this in the code text dialog and it seems to be working fine.  ?

**Comment by mirren** [comment]
Perhaps there was some influence of the previous problems in this, which are resolved now

Nevertheless, I tried again and it seemed like it works OK when I started coding but eventually later it broke down again.

In my case, breaking down happened during a coding session involving merging codes and marking/unmarking. 
I do not know if this is related but I was also switching between two coders in the process. 
Suddenly all counts changed value. 

By the way, what is the expected behaviour here? 

In the coding window, do counts correspond to the open file and coder (or all coders?)
And how is it in comparison to the reports window — do you have counts for all coders and files there?

**Comment by ccbogel** [comment]
In the code text counts - it is counts for the currently selected coder. - I can add a tooltip describing this
In the report window it is for all coders. - I can add a tooltip describing this

Code counts were ok when I marked/unmarked. I did not check merging

**Comment by ccbogel** [comment]
merging appears ok also

**Comment by mirren** [comment]
Some more concrete observations: 

1. The coder name in the coding window does not seem to be updated when a coder is changed; can you check?
2. I was able to code one word once for each of two coders and code count was two (should have been one if just codings from a single coder are displayed)
3, when unmarking the coding from one coder country remained one even though I was switching coders in preferences

**Comment by ccbogel** [comment]
Ah. iI thnk I am beginning to understand now.
So is this occuring: the code text window is open with a coders name there (say coder 1)
Then you open the Settings window and change to say coder 2
Then the code text window still shows coder 1

**Comment by mirren** [comment]
Yes this is happening so

**Comment by ccbogel** [comment]
OK - I had not considered this workflow.
OK, so now when the coder name is changed, all the other windows will be removed.
Then whatever window is next opened, it will have the current coder's name

**Comment by ccbogel** [comment]
I will close this issue for now. Please re open if it is still a problem.
