### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by WPFilmmaker** [ccbogel/QualCoder#285]
I have a decent level of Italian and would like to translate the GUI into Italian. I am not used to terminology in Italian as I use software in English but I think it could be a good starting point for future improvements by Italian academics :)

I saw qwertygc uploaded a french .po file, I tried searching for it but couldn't. @ccbogel could you give me such file so I translate and send it back?

**Comment by ccbogel** [comment]
@WPFilmmaker thanks for this. You need 2 files: The po file needs poedit to work. 
The ts file needs Qt Linguist:
sudo apt install python-setuptools
sudo apt install qttools5-dev-tools
sudo apt install qtcreator
sudo apt install qt5-doc

The app_it.ts file is located in the qualcoder/GUI folder
The it.po file is located in the qualcoder folder

Once translated, they need a further modification to convert to .qm and .mo files to work. I can do this.

**Comment by WPFilmmaker** [comment]
@ccbogel Thanks for the explanation, I tried in: /usr/share/qualcoder/GUI and /usr/share/qualcoder/locale but I can't find neither app_it nor it.po.

In /usr/share/qualcoder/locale/en/LC_MESSAGES I found an en.po but It has few lines which do not seem relevant.

Any idea?

**Comment by ccbogel** [comment]
I have uploaded those files to github, probably half an hour ago, so you need to download from there

________________________________

**Comment by ccbogel** [comment]
@WPFilmmaker please keep the formatting the same. so : . and any html tags.

**Comment by WPFilmmaker** [comment]
@ccbogel I have been busy, I will try this week and let you know how it goes.

**Comment by ccbogel** [comment]
@WPFilmmaker thanks yes. I have put it in place, with the .mo file. I wont offer the Italian option in the Settings yet. As need to wait until more is translated here and in the it.ts file.

**Comment by WPFilmmaker** [comment]
@ccbogel yes absolutely, was going to write that :)

**Comment by ccbogel** [comment]
@WPFilmmaker thank you. I notice in the it.po file for two untranslated strings there are Italian wording in the source text which should be in English. (Usare and Cambia la posizione di fine) Are you opening and editing this file with a standard text editor?

**Comment by WPFilmmaker** [comment]
@ccbogel Oops apologies for the mistake, were you able to fix it or can I do it next pull? I am not able to download any software atm so I just edited the po from github which worked ok.

**Comment by ccbogel** [comment]
Yes I fixed it

**Comment by WPFilmmaker** [comment]
@ccbogel qtlinguist throws me: Unexpected tag at /home/username/Downloads/app_it.ts:8:16 when I try to open app_it.ts
any idea?

**Comment by ccbogel** [comment]
@WPFilmmaker I have added a new ts file with a couple of translations in there. Maybe this will work better for you. It did open file for me.
If you still have problems then perhaps edit the original xml file in GitHub directly.

**Comment by WPFilmmaker** [comment]
@ccbogel it still throws the same errors, I will edit it from here and pull a merge request ;)

**Comment by ccbogel** [comment]
@WPFilmmaker Thansk for the translations - most are in the wrong location (in tags rather than between tags), so I will move them, LOL.

**Comment by WPFilmmaker** [comment]
@ccbogel you mean the one I just sent you? if yes then it it happened editing the file here and sending it, because I am sure I wrote them between the tags. Sorry for the inconvenience :/

ps: at row 106 attribute is spelt wrong, is it something you I can correct in the english string or should I leave it like that?

**Comment by ccbogel** [comment]
Thanks I will review it -I will need to fix the original spelling in another file. - row 106.
I am about to upload a fixed version - try again with QtLinguist - there was a missing quote symbol that might have cause the error

**Comment by WPFilmmaker** [comment]
@WPFilmmaker I tried again with the updated file but same error :/ maybe it is something wrong with Lubuntu. I will continue with github hoping it won't mess up the location again :)

I found the row (106):

        <source>Changes made on the top row will override any user changes to field names and field types below. Right-click on a column heading below to change the column name or to change from Character (atrtribute) to Qualitative (creates a text file from the text).</source>

**Comment by ccbogel** [comment]
completed
