### ISSUE TITLE
Bug: Categories/top categories by cases and transpose

### ISSUE THREAD

**Issue by AndrzejWawa** [ccbogel/QualCoder#702]
When you click categories/top categories by cases and transpose matrix the following error appears:

![obraz](https://user-images.githubusercontent.com/77200214/179375016-7249a5bc-251e-4e2e-bbeb-3e39c8d7925c.png)

**Comment by ccbogel** [comment]
This was fixed. download latest code to confirm

**Comment by AndrzejWawa** [comment]
There is still problem. I think it was fixed for code by file, but it is still problem for code by cases

**Comment by ccbogel** [comment]
I have tested now - and I have no problem. can you download latest code and try again ?

**Comment by AndrzejWawa** [comment]
Hmm, still have problem. Are you sure that you selected exactly the same options, that are:

1) Top categories by case or categories by case and
2) Transpose matrix.

Because, the problem is only when you also select transpose matrix. Like in the picture.

![obraz](https://user-images.githubusercontent.com/77200214/179394748-cf348425-0cd4-48d9-b5d2-9875af008188.png)

**Comment by AndrzejWawa** [comment]
So, you are sure that you tried top categories by case with selecting "transpose matrix"?

**Comment by ccbogel** [comment]
HI I tried all options. Then I realised the problem. It was in the selection of codes and categories. Selecting a top level code (a code without a category) caused the problem. Latest code should fix this.
